# Generated by Django 3.2.16 on 2023-07-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230729_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publication',
            new_name='post',
        ),
    ]
